Support for  downloading File Uploads to Private Filedisks
lara-zeus/bolt pull request #334
Opened 2024-12-12 12:10 UTC by aSeriousDeveloper

File uploads in Bolt are broken when attempting to view if you use a private filesystem. This is because it does not generate a temporary URL. This PR resolves that by using a closure to generate the URL, and checking whether the currently configured disk is public or private.

Additionally, I've added 3 new environment variables (with default values matching original config):
- `BOLT_FILESYSTEM_DISK`
- `BOLT_FILESYSTEM_PREFIX`
- `BOLT_FILESYSTEM_VISIBILITY`

2024-12-22 16:30 UTC, atmonshi requested changes
sorry for the delay.

2024-12-22 16:30 UTC, atmonshi commented on config/zeus-bolt.php
> +    'uploadDirectory' => env('BOLT_FILESYSTEM_PREFIX', 'forms'),
sorry for the delay.
prefer `DIRECTORY` over `PREFIX` :)

2024-12-23 12:58 UTC, aSeriousDeveloper commented
Changed to DIRECTORY instead of PREFIX

2024-12-24 16:53 UTC, atmonshi approved these changes

2024-12-24 17:02 UTC, merged